
version: "1.0"

services:
  
  flask-server:
    container_name: flask-server 
    build: 
      context: ./app 
      dockerfile: Dockerfile 
    volumes: 
      - ./app:/var/app/flask_app 
    ports:
      - "5000:50505"
  



