name: 'azTemplateDeployment'
description: 'depligue de arm template en azure en un resource group'
inputs:
  AZURE_CREDENTIALS:
    required: true

  SUBSCRIPTION_NAME:
    required: true

  location:
    required: true

  resource_group:
    required: true

  ARM_TEMPLATE:
    required: true

outputs:
  my_output:
    description: 'deployment succeed'


runs:
  using: "composite"
  shell: ubuntu-latest
  steps:
        - name: Checkout code
          uses: actions/checkout@v4
          shell: bash
    
        - name: azure login
          uses: azure/login@v2
          with:
           creds: ${{ inputs.AZURE_CREDENTIALS }}
          shell: bash
        
        - name: azure set subscription
          run: |
            az account set --subscription ${{inputs.SUBSCRIPTION_NAME}}
          shell: bash
        
        - name: azure rs creation
          run: |
            az group create --name ${{inputs.resource-group}} --location ${{inputs.location}}
          shell: bash
        
        - name: deployment
          run: |
            az deployment group  create  --resource-group ${{inputs.resource-group}}  --template-file ${{inputs.ARM_TEMPLATE}}
          shell: bash
