name: 'azTemplateDeployment'
description: 'depligue de arm template en azure en un resource group'
inputs:
  AZURE_CREDENTIALS:
    description: "service principal, contiene clientID, tenantID, password"
    required: true
  SUBSCRIPTION_NAME:
    description: "nombre subscription en azure"
    required: true
  location:
    description: "region del resource group"
    required: true
  resource_group:
    description: "nombre del resource group donde se despliegan los servicios"
    required: true
  ARM_TEMPLATE:
    description: "arm template json"
    required: true
  parametros_file:
    description: "arm template parameters json"
    required: true


runs:
  using: "composite"
  steps:

    
        - name: azure login
          uses: azure/login@v2
          with:
           creds: ${{ inputs.AZURE_CREDENTIALS }}
        
        - name: azure set subscription
          run: |
            az account set --subscription ${{inputs.SUBSCRIPTION_NAME}}
          shell: bash
        
        - name: azure rs creation
          run: |
            az group create --name ${{inputs.resource_group}} --location ${{inputs.location}}
          shell: bash
        
        - name: deployment
          run: |
            az deployment group  create  --resource-group ${{inputs.resource_group}}  --template-file ${{inputs.ARM_TEMPLATE}} --parameters {{inputs.parametros_file}}
          shell: bash
