name: resourcegroup_deployment
on: 
    push
env:
   ARM_TEMPLATE_CONTAINER: IaC/container_registry.json
   name: lol
   SUBSCRIPTION_ID: ${{ secrets.SUBSCRIBE_ID}}
   location: uksouth
   resource-group: az_tiempo 
   parameter_file : IaC/param_container.json

jobs:

    deployment:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          
          - name: nuevo deploy
            uses: ./.github/actions/azTemplateP
            with:
              AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
              SUBSCRIPTION_NAME: ${{secrets.SUBSCRIPTION_NAME}}
              location: ${{env.location}}
              resource_group: ${{env.resource-group}}
              ARM_TEMPLATE: ${{env.ARM_TEMPLATE_CONTAINER}}
              parametros_file: ${{env.parameter_file}}

            